DEBUG 2017-08-06 13:21:56,928 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'debug' in template 'admin/login.html'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [debug] in u'[{\'False\': False, \'None\': None, \'True\': True}, {u\'csrf_token\': <SimpleLazyObject: <function _get_val at 0x3ef9488>>, \'user\': <SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x3e37810>>, \'perms\': <django.contrib.auth.context_processors.PermWrapper object at 0x3ef3d10>, \'DEFAULT_MESSAGE_LEVELS\': {\'DEBUG\': 10, \'INFO\': 20, \'WARNING\': 30, \'SUCCESS\': 25, \'ERROR\': 40}, \'messages\': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x3e37350>, u\'request\': <WSGIRequest: GET \'/admin/login/?next=/admin/enjoy_love/\'>}, {}, {\'username\': u\'\', \'app_path\': u\'/admin/login/?next=/admin/enjoy_love/\', \'available_apps\': [], \'site_name\': \'app1\', \'form\': <AdminAuthenticationForm bound=False, valid=Unknown, fields=(username;password)>, \'title\': u\'\\u767b\\u5f55\', \'site_header\': u\'Django \\u7ba1\\u7406\', \'site\': <django.contrib.sites.requests.RequestSite object at 0x3e37ed0>, \'next\': u\'/admin/enjoy_love/\', \'site_title\': u\'Django \\u7ad9\\u70b9\\u7ba1\\u7406\\u5458\', u\'LANGUAGE_CODE\': u\'zh-hans\', \'has_permission\': False, \'site_url\': \'/\', u\'LANGUAGE_BIDI\': False, u\'view\': <django.contrib.auth.views.LoginView object at 0x3e37a50>}, {\'block\': <Block Node: javascripts. Contents: [<TextNode: u\'\\n        <script type="te\'>, <django.template.defaulttags.FilterNode object at 0x3efe750>, <TextNode: u\'";</script>\\n        <scri\'>, <django.template.defaulttags.FilterNode object at 0x3efe890>, <TextNode: u\'";</script>\\n        <scri\'>, <django.template.defaulttags.URLNode object at 0x3f802d0>, <TextNode: u\'",\\n                MODEL_\'>, <IfNode>, <TextNode: u\',\\n                DATE_FO\'>, <django.template.library.SimpleNode object at 0x3f80550>, <TextNode: u\'",\\n                TIME_F\'>, <django.template.library.SimpleNode object at 0x3f805d0>, <TextNode: u\'",\\n                DATETI\'>, <django.template.library.SimpleNode object at 0x3f80650>, <TextNode: u\'";\\n        </script>\\n    \'>, <django.template.library.SimpleNode object at 0x3f806d0>, <TextNode: u\'" type="text/javascript">\'>, <django.template.library.SimpleNode object at 0x3f80790>, <TextNode: u\'" type="text/javascript">\'>, <IfNode>, <TextNode: u\'\\n        <script type="te\'>]>}]'
DEBUG 2017-08-06 13:21:56,929 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'is_popup' in template 'admin/login.html'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [is_popup] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x3ef9488>>, 'user': <SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x3e37810>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x3ef3d10>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x3e37350>, u'request': <WSGIRequest: GET '/admin/login/?next=/admin/enjoy_love/'>}, {}, {'username': u'', 'app_path': u'/admin/login/?next=/admin/enjoy_love/', 'available_apps': [], 'site_name': 'app1', 'form': <AdminAuthenticationForm bound=False, valid=Unknown, fields=(username;password)>, 'title': u'\\u767b\\u5f55', 'site_header': u'Django \\u7ba1\\u7406', 'site': <django.contrib.sites.requests.RequestSite object at 0x3e37ed0>, 'next': u'/admin/enjoy_love/', 'site_title': u'Django \\u7ad9\\u70b9\\u7ba1\\u7406\\u5458', u'LANGUAGE_CODE': u'zh-hans', 'has_permission': False, 'site_url': '/', u'LANGUAGE_BIDI': False, u'view': <django.contrib.auth.views.LoginView object at 0x3e37a50>}]"
DEBUG 2017-08-06 13:21:56,930 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'is_popup' in template 'admin/login.html'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [is_popup] in u'[{\'False\': False, \'None\': None, \'True\': True}, {u\'csrf_token\': <SimpleLazyObject: <function _get_val at 0x3ef9488>>, \'user\': <SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x3e37810>>, \'perms\': <django.contrib.auth.context_processors.PermWrapper object at 0x3ef3d10>, \'DEFAULT_MESSAGE_LEVELS\': {\'DEBUG\': 10, \'INFO\': 20, \'WARNING\': 30, \'SUCCESS\': 25, \'ERROR\': 40}, \'messages\': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x3e37350>, u\'request\': <WSGIRequest: GET \'/admin/login/?next=/admin/enjoy_love/\'>}, {}, {\'username\': u\'\', \'app_path\': u\'/admin/login/?next=/admin/enjoy_love/\', \'available_apps\': [], \'site_name\': \'app1\', \'form\': <AdminAuthenticationForm bound=False, valid=Unknown, fields=(username;password)>, \'title\': u\'\\u767b\\u5f55\', \'site_header\': u\'Django \\u7ba1\\u7406\', \'site\': <django.contrib.sites.requests.RequestSite object at 0x3e37ed0>, \'next\': u\'/admin/enjoy_love/\', \'site_title\': u\'Django \\u7ad9\\u70b9\\u7ba1\\u7406\\u5458\', u\'LANGUAGE_CODE\': u\'zh-hans\', \'has_permission\': False, \'site_url\': \'/\', u\'LANGUAGE_BIDI\': False, u\'view\': <django.contrib.auth.views.LoginView object at 0x3e37a50>}, {\'block\': <Block Node: header. Contents: [<TextNode: u\'\\n            <!-- HEADER \'>, <Block Node: header-class. Contents: []>, <TextNode: u\'">\\n                \'>, <IfNode>, <TextNode: u\'\\n            </header>\\n  \'>]>}]'
DEBUG 2017-08-06 13:21:56,931 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'grappelli_admin_title' in template 'admin/login.html'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [grappelli_admin_title] in u'[{\'False\': False, \'None\': None, \'True\': True}, {u\'csrf_token\': <SimpleLazyObject: <function _get_val at 0x3ef9488>>, \'user\': <SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x3e37810>>, \'perms\': <django.contrib.auth.context_processors.PermWrapper object at 0x3ef3d10>, \'DEFAULT_MESSAGE_LEVELS\': {\'DEBUG\': 10, \'INFO\': 20, \'WARNING\': 30, \'SUCCESS\': 25, \'ERROR\': 40}, \'messages\': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x3e37350>, u\'request\': <WSGIRequest: GET \'/admin/login/?next=/admin/enjoy_love/\'>}, {}, {\'username\': u\'\', \'app_path\': u\'/admin/login/?next=/admin/enjoy_love/\', \'available_apps\': [], \'site_name\': \'app1\', \'form\': <AdminAuthenticationForm bound=False, valid=Unknown, fields=(username;password)>, \'title\': u\'\\u767b\\u5f55\', \'site_header\': u\'Django \\u7ba1\\u7406\', \'site\': <django.contrib.sites.requests.RequestSite object at 0x3e37ed0>, \'next\': u\'/admin/enjoy_love/\', \'site_title\': u\'Django \\u7ad9\\u70b9\\u7ba1\\u7406\\u5458\', u\'LANGUAGE_CODE\': u\'zh-hans\', \'has_permission\': False, \'site_url\': \'/\', u\'LANGUAGE_BIDI\': False, u\'view\': <django.contrib.auth.views.LoginView object at 0x3e37a50>}, {\'block\': <Block Node: header. Contents: [<TextNode: u\'\\n            <!-- HEADER \'>, <Block Node: header-class. Contents: []>, <TextNode: u\'">\\n                \'>, <IfNode>, <TextNode: u\'\\n            </header>\\n  \'>]>}, {\'block\': <Block Node: navigation. Contents: [<TextNode: u\'\\n                        \'>, <Block Node: branding. Contents: []>, <TextNode: u\'\\n                        \'>, <Block Node: admin_title. Contents: [<TextNode: u\'<h1 id="grp-admin-title">\'>, <IfNode>, <TextNode: u\'</h1>\'>]>, <TextNode: u\'\\n                        \'>, <Block Node: user-tools. Contents: [<TextNode: u\'\\n                        \'>, <IfNode>, <TextNode: u\'\\n                        \'>]>, <TextNode: u\'\\n                        \'>, <Block Node: nav-global. Contents: []>, <TextNode: u\'\\n                        \'>]>}, {\'block\': <Block Node: admin_title. Contents: [<TextNode: u\'<h1 id="grp-admin-title">\'>, <IfNode>, <TextNode: u\'</h1>\'>]>}]'
DEBUG 2017-08-06 13:21:56,934 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'grappelli_admin_title' in template 'admin/login.html'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [grappelli_admin_title] in u'[{\'False\': False, \'None\': None, \'True\': True}, {u\'csrf_token\': <SimpleLazyObject: u\'h2Gv2hrPYoEhGebdYELg95s2YXCtu4OBFOWmOftveWYob6Ltfh7i3h2YsPkHGeRM\'>, \'user\': <SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x3e37810>>, \'perms\': <django.contrib.auth.context_processors.PermWrapper object at 0x3ef3d10>, \'DEFAULT_MESSAGE_LEVELS\': {\'DEBUG\': 10, \'INFO\': 20, \'WARNING\': 30, \'SUCCESS\': 25, \'ERROR\': 40}, \'messages\': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x3e37350>, u\'request\': <WSGIRequest: GET \'/admin/login/?next=/admin/enjoy_love/\'>}, {}, {\'username\': u\'\', \'app_path\': u\'/admin/login/?next=/admin/enjoy_love/\', \'available_apps\': [], \'site_name\': \'app1\', \'form\': <AdminAuthenticationForm bound=False, valid=Unknown, fields=(username;password)>, \'title\': u\'\\u767b\\u5f55\', \'site_header\': u\'Django \\u7ba1\\u7406\', \'site\': <django.contrib.sites.requests.RequestSite object at 0x3e37ed0>, \'next\': u\'/admin/enjoy_love/\', \'site_title\': u\'Django \\u7ad9\\u70b9\\u7ba1\\u7406\\u5458\', u\'LANGUAGE_CODE\': u\'zh-hans\', \'has_permission\': False, \'site_url\': \'/\', u\'LANGUAGE_BIDI\': False, u\'view\': <django.contrib.auth.views.LoginView object at 0x3e37a50>}, {\'block\': <Block Node: content. Contents: [<TextNode: u\'\\n    <div class="g-d-c g-\'>, <Variable Node: app_path>, <TextNode: u\'" method="post" novalidat\'>, <django.template.defaulttags.CsrfTokenNode object at 0x3eef410>, <TextNode: u\'\\n            <fieldset cl\'>, <IfNode>, <TextNode: u\'</span>\\n                 \'>, <django.templatetags.i18n.TranslateNode object at 0x3eef750>, <TextNode: u\'</span>\\n                <\'>, <IfNode>, <TextNode: u\'\\n                    \'>, <IfNode>, <TextNode: u\'\\n                    \'>, <IfNode>, <TextNode: u\'\\n                    <div\'>, <IfNode>, <TextNode: u\'">\\n                      \'>, <Variable Node: form.username.label>, <TextNode: u\'</label>\\n                \'>, <IfNode>, <TextNode: u\'\\n                    </di\'>, <IfNode>, <TextNode: u\'">\\n                      \'>, <Variable Node: form.password.label>, <TextNode: u\'</label>\\n                \'>, <Variable Node: next>, <TextNode: u\'" />\\n                    \'>, <IfNode>, <TextNode: u\'\\n                    </di\'>, <django.template.defaulttags.URLNode object at 0x3ef2e50>, <TextNode: u\'\\n                    \'>, <IfNode>, <TextNode: u\'\\n                </div>\\n \'>, <django.templatetags.i18n.TranslateNode object at 0x3ef3290>, <TextNode: u\'" /></li>\\n               \'>]>}]'
DEBUG 2017-08-06 13:21:56,934 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'error_message' in template 'admin/login.html'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error_message] in u'[{\'False\': False, \'None\': None, \'True\': True}, {u\'csrf_token\': <SimpleLazyObject: u\'h2Gv2hrPYoEhGebdYELg95s2YXCtu4OBFOWmOftveWYob6Ltfh7i3h2YsPkHGeRM\'>, \'user\': <SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x3e37810>>, \'perms\': <django.contrib.auth.context_processors.PermWrapper object at 0x3ef3d10>, \'DEFAULT_MESSAGE_LEVELS\': {\'DEBUG\': 10, \'INFO\': 20, \'WARNING\': 30, \'SUCCESS\': 25, \'ERROR\': 40}, \'messages\': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x3e37350>, u\'request\': <WSGIRequest: GET \'/admin/login/?next=/admin/enjoy_love/\'>}, {}, {\'username\': u\'\', \'app_path\': u\'/admin/login/?next=/admin/enjoy_love/\', \'available_apps\': [], \'site_name\': \'app1\', \'form\': <AdminAuthenticationForm bound=False, valid=False, fields=(username;password)>, \'title\': u\'\\u767b\\u5f55\', \'site_header\': u\'Django \\u7ba1\\u7406\', \'site\': <django.contrib.sites.requests.RequestSite object at 0x3e37ed0>, \'next\': u\'/admin/enjoy_love/\', \'site_title\': u\'Django \\u7ad9\\u70b9\\u7ba1\\u7406\\u5458\', u\'LANGUAGE_CODE\': u\'zh-hans\', \'has_permission\': False, \'site_url\': \'/\', u\'LANGUAGE_BIDI\': False, u\'view\': <django.contrib.auth.views.LoginView object at 0x3e37a50>}, {\'block\': <Block Node: content. Contents: [<TextNode: u\'\\n    <div class="g-d-c g-\'>, <Variable Node: app_path>, <TextNode: u\'" method="post" novalidat\'>, <django.template.defaulttags.CsrfTokenNode object at 0x3eef410>, <TextNode: u\'\\n            <fieldset cl\'>, <IfNode>, <TextNode: u\'</span>\\n                 \'>, <django.templatetags.i18n.TranslateNode object at 0x3eef750>, <TextNode: u\'</span>\\n                <\'>, <IfNode>, <TextNode: u\'\\n                    \'>, <IfNode>, <TextNode: u\'\\n                    \'>, <IfNode>, <TextNode: u\'\\n                    <div\'>, <IfNode>, <TextNode: u\'">\\n                      \'>, <Variable Node: form.username.label>, <TextNode: u\'</label>\\n                \'>, <IfNode>, <TextNode: u\'\\n                    </di\'>, <IfNode>, <TextNode: u\'">\\n                      \'>, <Variable Node: form.password.label>, <TextNode: u\'</label>\\n                \'>, <Variable Node: next>, <TextNode: u\'" />\\n                    \'>, <IfNode>, <TextNode: u\'\\n                    </di\'>, <django.template.defaulttags.URLNode object at 0x3ef2e50>, <TextNode: u\'\\n                    \'>, <IfNode>, <TextNode: u\'\\n                </div>\\n \'>, <django.templatetags.i18n.TranslateNode object at 0x3ef3290>, <TextNode: u\'" /></li>\\n               \'>]>}]'
