DEBUG 2017-08-18 07:00:43,145 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'grappelli.urls' from '/root/enjoylove/lib/python2.7/site-packages/grappelli/urls.pyc'> (None:None) ^grappelli/>"
DEBUG 2017-08-18 07:00:43,146 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
DEBUG 2017-08-18 07:00:43,146 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework/urls.pyc'> (rest_framework:rest_framework) ^api-auth/>"
DEBUG 2017-08-18 07:00:43,147 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'enjoy_love.urls' from '/root/enjoylove/enjoylove/enjoy_love/urls.pyc'> (None:None) ^user/>"
DEBUG 2017-08-18 07:00:43,148 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework_docs.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework_docs/urls.pyc'> (None:None) ^docs/>"
DEBUG 2017-08-18 07:00:43,259 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'grappelli.urls' from '/root/enjoylove/lib/python2.7/site-packages/grappelli/urls.pyc'> (None:None) ^grappelli/>"
DEBUG 2017-08-18 07:00:43,260 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
DEBUG 2017-08-18 07:00:43,260 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework/urls.pyc'> (rest_framework:rest_framework) ^api-auth/>"
DEBUG 2017-08-18 07:00:43,260 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'enjoy_love.urls' from '/root/enjoylove/enjoylove/enjoy_love/urls.pyc'> (None:None) ^user/>"
DEBUG 2017-08-18 07:00:43,261 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework_docs.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework_docs/urls.pyc'> (None:None) ^docs/>"
DEBUG 2017-08-18 07:00:43,339 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'grappelli.urls' from '/root/enjoylove/lib/python2.7/site-packages/grappelli/urls.pyc'> (None:None) ^grappelli/>"
DEBUG 2017-08-18 07:00:43,340 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
DEBUG 2017-08-18 07:00:43,340 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework/urls.pyc'> (rest_framework:rest_framework) ^api-auth/>"
DEBUG 2017-08-18 07:00:43,340 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'enjoy_love.urls' from '/root/enjoylove/enjoylove/enjoy_love/urls.pyc'> (None:None) ^user/>"
DEBUG 2017-08-18 07:00:43,341 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework_docs.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework_docs/urls.pyc'> (None:None) ^docs/>"
DEBUG 2017-08-18 07:00:43,422 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'grappelli.urls' from '/root/enjoylove/lib/python2.7/site-packages/grappelli/urls.pyc'> (None:None) ^grappelli/>"
DEBUG 2017-08-18 07:00:43,423 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
DEBUG 2017-08-18 07:00:43,423 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework/urls.pyc'> (rest_framework:rest_framework) ^api-auth/>"
DEBUG 2017-08-18 07:00:43,424 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'enjoy_love.urls' from '/root/enjoylove/enjoylove/enjoy_love/urls.pyc'> (None:None) ^user/>"
DEBUG 2017-08-18 07:00:43,424 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework_docs.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework_docs/urls.pyc'> (None:None) ^docs/>"
DEBUG 2017-08-18 07:00:43,499 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'grappelli.urls' from '/root/enjoylove/lib/python2.7/site-packages/grappelli/urls.pyc'> (None:None) ^grappelli/>"
DEBUG 2017-08-18 07:00:43,500 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
DEBUG 2017-08-18 07:00:43,500 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework/urls.pyc'> (rest_framework:rest_framework) ^api-auth/>"
DEBUG 2017-08-18 07:00:43,500 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'enjoy_love.urls' from '/root/enjoylove/enjoylove/enjoy_love/urls.pyc'> (None:None) ^user/>"
DEBUG 2017-08-18 07:00:43,501 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework_docs.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework_docs/urls.pyc'> (None:None) ^docs/>"
DEBUG 2017-08-18 07:00:43,726 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'grappelli.urls' from '/root/enjoylove/lib/python2.7/site-packages/grappelli/urls.pyc'> (None:None) ^grappelli/>"
DEBUG 2017-08-18 07:00:43,727 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
DEBUG 2017-08-18 07:00:43,728 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework/urls.pyc'> (rest_framework:rest_framework) ^api-auth/>"
DEBUG 2017-08-18 07:00:43,728 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'enjoy_love.urls' from '/root/enjoylove/enjoylove/enjoy_love/urls.pyc'> (None:None) ^user/>"
DEBUG 2017-08-18 07:00:43,729 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework_docs.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework_docs/urls.pyc'> (None:None) ^docs/>"
DEBUG 2017-08-18 07:00:43,811 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'grappelli.urls' from '/root/enjoylove/lib/python2.7/site-packages/grappelli/urls.pyc'> (None:None) ^grappelli/>"
DEBUG 2017-08-18 07:00:43,812 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
DEBUG 2017-08-18 07:00:43,812 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework/urls.pyc'> (rest_framework:rest_framework) ^api-auth/>"
DEBUG 2017-08-18 07:00:43,813 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'enjoy_love.urls' from '/root/enjoylove/enjoylove/enjoy_love/urls.pyc'> (None:None) ^user/>"
DEBUG 2017-08-18 07:00:43,813 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework_docs.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework_docs/urls.pyc'> (None:None) ^docs/>"
DEBUG 2017-08-18 07:00:43,886 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'grappelli.urls' from '/root/enjoylove/lib/python2.7/site-packages/grappelli/urls.pyc'> (None:None) ^grappelli/>"
DEBUG 2017-08-18 07:00:43,887 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
DEBUG 2017-08-18 07:00:43,887 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework/urls.pyc'> (rest_framework:rest_framework) ^api-auth/>"
DEBUG 2017-08-18 07:00:43,888 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'enjoy_love.urls' from '/root/enjoylove/enjoylove/enjoy_love/urls.pyc'> (None:None) ^user/>"
DEBUG 2017-08-18 07:00:43,888 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework_docs.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework_docs/urls.pyc'> (None:None) ^docs/>"
DEBUG 2017-08-18 07:00:43,996 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'grappelli.urls' from '/root/enjoylove/lib/python2.7/site-packages/grappelli/urls.pyc'> (None:None) ^grappelli/>"
DEBUG 2017-08-18 07:00:43,996 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
DEBUG 2017-08-18 07:00:43,997 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework/urls.pyc'> (rest_framework:rest_framework) ^api-auth/>"
DEBUG 2017-08-18 07:00:43,998 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'enjoy_love.urls' from '/root/enjoylove/enjoylove/enjoy_love/urls.pyc'> (None:None) ^user/>"
DEBUG 2017-08-18 07:00:43,998 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework_docs.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework_docs/urls.pyc'> (None:None) ^docs/>"
DEBUG 2017-08-18 07:00:44,228 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'grappelli.urls' from '/root/enjoylove/lib/python2.7/site-packages/grappelli/urls.pyc'> (None:None) ^grappelli/>"
DEBUG 2017-08-18 07:00:44,229 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
DEBUG 2017-08-18 07:00:44,229 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework/urls.pyc'> (rest_framework:rest_framework) ^api-auth/>"
DEBUG 2017-08-18 07:00:44,230 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'enjoy_love.urls' from '/root/enjoylove/enjoylove/enjoy_love/urls.pyc'> (None:None) ^user/>"
DEBUG 2017-08-18 07:00:44,230 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework_docs.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework_docs/urls.pyc'> (None:None) ^docs/>"
DEBUG 2017-08-18 07:00:44,480 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'grappelli.urls' from '/root/enjoylove/lib/python2.7/site-packages/grappelli/urls.pyc'> (None:None) ^grappelli/>"
DEBUG 2017-08-18 07:00:44,481 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
DEBUG 2017-08-18 07:00:44,481 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework/urls.pyc'> (rest_framework:rest_framework) ^api-auth/>"
DEBUG 2017-08-18 07:00:44,482 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'enjoy_love.urls' from '/root/enjoylove/enjoylove/enjoy_love/urls.pyc'> (None:None) ^user/>"
DEBUG 2017-08-18 07:00:44,483 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework_docs.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework_docs/urls.pyc'> (None:None) ^docs/>"
DEBUG 2017-08-18 07:00:44,612 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'grappelli.urls' from '/root/enjoylove/lib/python2.7/site-packages/grappelli/urls.pyc'> (None:None) ^grappelli/>"
DEBUG 2017-08-18 07:00:44,613 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
DEBUG 2017-08-18 07:00:44,613 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework/urls.pyc'> (rest_framework:rest_framework) ^api-auth/>"
DEBUG 2017-08-18 07:00:44,614 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'enjoy_love.urls' from '/root/enjoylove/enjoylove/enjoy_love/urls.pyc'> (None:None) ^user/>"
DEBUG 2017-08-18 07:00:44,614 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework_docs.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework_docs/urls.pyc'> (None:None) ^docs/>"
DEBUG 2017-08-18 07:00:45,015 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'grappelli.urls' from '/root/enjoylove/lib/python2.7/site-packages/grappelli/urls.pyc'> (None:None) ^grappelli/>"
DEBUG 2017-08-18 07:00:45,016 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
DEBUG 2017-08-18 07:00:45,016 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework/urls.pyc'> (rest_framework:rest_framework) ^api-auth/>"
DEBUG 2017-08-18 07:00:45,017 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'enjoy_love.urls' from '/root/enjoylove/enjoylove/enjoy_love/urls.pyc'> (None:None) ^user/>"
DEBUG 2017-08-18 07:00:45,018 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework_docs.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework_docs/urls.pyc'> (None:None) ^docs/>"
DEBUG 2017-08-18 07:00:45,101 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'grappelli.urls' from '/root/enjoylove/lib/python2.7/site-packages/grappelli/urls.pyc'> (None:None) ^grappelli/>"
DEBUG 2017-08-18 07:00:45,101 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
DEBUG 2017-08-18 07:00:45,102 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework/urls.pyc'> (rest_framework:rest_framework) ^api-auth/>"
DEBUG 2017-08-18 07:00:45,102 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'enjoy_love.urls' from '/root/enjoylove/enjoylove/enjoy_love/urls.pyc'> (None:None) ^user/>"
DEBUG 2017-08-18 07:00:45,102 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework_docs.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework_docs/urls.pyc'> (None:None) ^docs/>"
DEBUG 2017-08-18 07:00:45,179 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'grappelli.urls' from '/root/enjoylove/lib/python2.7/site-packages/grappelli/urls.pyc'> (None:None) ^grappelli/>"
DEBUG 2017-08-18 07:00:45,181 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (None:None) ^auth/group/>'
DEBUG 2017-08-18 07:00:45,181 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (None:None) ^enjoy_love/filtercontrol/>'
DEBUG 2017-08-18 07:00:45,182 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (None:None) ^enjoy_love/personaltag/>'
DEBUG 2017-08-18 07:00:45,182 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (None:None) ^authtoken/token/>'
DEBUG 2017-08-18 07:00:45,183 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (None:None) ^enjoy_love/globalsettings/>'
DEBUG 2017-08-18 07:00:45,183 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (None:None) ^enjoy_love/advertisement/>'
DEBUG 2017-08-18 07:00:45,184 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (None:None) ^auth/user/>'
DEBUG 2017-08-18 07:00:45,184 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (None:None) ^enjoy_love/personalinterest/>'
DEBUG 2017-08-18 07:00:45,184 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (None:None) ^enjoy_love/vip/>'
DEBUG 2017-08-18 07:00:45,185 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (None:None) ^enjoy_love/identityverify/>'
DEBUG 2017-08-18 07:00:45,185 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (None:None) ^enjoy_love/contacttype/>'
DEBUG 2017-08-18 07:00:45,186 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework/urls.pyc'> (rest_framework:rest_framework) ^api-auth/>"
DEBUG 2017-08-18 07:00:45,187 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'enjoy_love.urls' from '/root/enjoylove/enjoylove/enjoy_love/urls.pyc'> (None:None) ^user/>"
DEBUG 2017-08-18 07:00:45,187 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework_docs.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework_docs/urls.pyc'> (None:None) ^docs/>"
DEBUG 2017-08-18 07:00:45,402 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'grappelli.urls' from '/root/enjoylove/lib/python2.7/site-packages/grappelli/urls.pyc'> (None:None) ^grappelli/>"
DEBUG 2017-08-18 07:00:45,404 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (None:None) ^auth/group/>'
DEBUG 2017-08-18 07:00:45,405 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (None:None) ^enjoy_love/filtercontrol/>'
DEBUG 2017-08-18 07:00:45,405 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (None:None) ^enjoy_love/personaltag/>'
DEBUG 2017-08-18 07:00:45,406 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (None:None) ^authtoken/token/>'
DEBUG 2017-08-18 07:00:45,407 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (None:None) ^enjoy_love/globalsettings/>'
DEBUG 2017-08-18 07:00:45,408 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (None:None) ^enjoy_love/advertisement/>'
DEBUG 2017-08-18 07:00:45,408 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (None:None) ^auth/user/>'
DEBUG 2017-08-18 07:00:45,409 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (None:None) ^enjoy_love/personalinterest/>'
DEBUG 2017-08-18 07:00:45,409 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (None:None) ^enjoy_love/vip/>'
DEBUG 2017-08-18 07:00:45,410 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (None:None) ^enjoy_love/identityverify/>'
DEBUG 2017-08-18 07:00:45,411 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (None:None) ^enjoy_love/contacttype/>'
DEBUG 2017-08-18 07:00:45,412 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework/urls.pyc'> (rest_framework:rest_framework) ^api-auth/>"
DEBUG 2017-08-18 07:00:45,412 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'enjoy_love.urls' from '/root/enjoylove/enjoylove/enjoy_love/urls.pyc'> (None:None) ^user/>"
DEBUG 2017-08-18 07:00:45,413 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework_docs.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework_docs/urls.pyc'> (None:None) ^docs/>"
DEBUG 2017-08-18 07:00:45,632 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'grappelli.urls' from '/root/enjoylove/lib/python2.7/site-packages/grappelli/urls.pyc'> (None:None) ^grappelli/>"
DEBUG 2017-08-18 07:00:45,634 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (None:None) ^auth/group/>'
DEBUG 2017-08-18 07:00:45,634 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (None:None) ^enjoy_love/filtercontrol/>'
DEBUG 2017-08-18 07:00:45,635 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (None:None) ^enjoy_love/personaltag/>'
DEBUG 2017-08-18 07:00:45,635 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (None:None) ^authtoken/token/>'
DEBUG 2017-08-18 07:00:45,636 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (None:None) ^enjoy_love/globalsettings/>'
DEBUG 2017-08-18 07:00:45,636 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (None:None) ^enjoy_love/advertisement/>'
DEBUG 2017-08-18 07:00:45,637 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (None:None) ^auth/user/>'
DEBUG 2017-08-18 07:00:45,637 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (None:None) ^enjoy_love/personalinterest/>'
DEBUG 2017-08-18 07:00:45,638 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (None:None) ^enjoy_love/vip/>'
DEBUG 2017-08-18 07:00:45,638 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (None:None) ^enjoy_love/identityverify/>'
DEBUG 2017-08-18 07:00:45,639 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (None:None) ^enjoy_love/contacttype/>'
DEBUG 2017-08-18 07:00:45,640 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework/urls.pyc'> (rest_framework:rest_framework) ^api-auth/>"
DEBUG 2017-08-18 07:00:45,640 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'enjoy_love.urls' from '/root/enjoylove/enjoylove/enjoy_love/urls.pyc'> (None:None) ^user/>"
DEBUG 2017-08-18 07:00:45,641 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework_docs.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework_docs/urls.pyc'> (None:None) ^docs/>"
DEBUG 2017-08-18 07:00:45,797 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'grappelli.urls' from '/root/enjoylove/lib/python2.7/site-packages/grappelli/urls.pyc'> (None:None) ^grappelli/>"
DEBUG 2017-08-18 07:00:45,799 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (None:None) ^auth/group/>'
DEBUG 2017-08-18 07:00:45,800 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (None:None) ^enjoy_love/filtercontrol/>'
DEBUG 2017-08-18 07:00:45,800 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (None:None) ^enjoy_love/personaltag/>'
DEBUG 2017-08-18 07:00:45,800 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (None:None) ^authtoken/token/>'
DEBUG 2017-08-18 07:00:45,801 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (None:None) ^enjoy_love/globalsettings/>'
DEBUG 2017-08-18 07:00:45,801 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (None:None) ^enjoy_love/advertisement/>'
DEBUG 2017-08-18 07:00:45,802 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (None:None) ^auth/user/>'
DEBUG 2017-08-18 07:00:45,802 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (None:None) ^enjoy_love/personalinterest/>'
DEBUG 2017-08-18 07:00:45,803 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (None:None) ^enjoy_love/vip/>'
DEBUG 2017-08-18 07:00:45,803 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (None:None) ^enjoy_love/identityverify/>'
DEBUG 2017-08-18 07:00:45,804 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (None:None) ^enjoy_love/contacttype/>'
DEBUG 2017-08-18 07:00:45,804 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework/urls.pyc'> (rest_framework:rest_framework) ^api-auth/>"
DEBUG 2017-08-18 07:00:45,805 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'enjoy_love.urls' from '/root/enjoylove/enjoylove/enjoy_love/urls.pyc'> (None:None) ^user/>"
DEBUG 2017-08-18 07:00:45,805 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework_docs.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework_docs/urls.pyc'> (None:None) ^docs/>"
DEBUG 2017-08-18 07:00:46,087 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'grappelli.urls' from '/root/enjoylove/lib/python2.7/site-packages/grappelli/urls.pyc'> (None:None) ^grappelli/>"
DEBUG 2017-08-18 07:00:46,089 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (None:None) ^auth/group/>'
DEBUG 2017-08-18 07:00:46,090 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (None:None) ^enjoy_love/filtercontrol/>'
DEBUG 2017-08-18 07:00:46,090 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (None:None) ^enjoy_love/personaltag/>'
DEBUG 2017-08-18 07:00:46,091 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (None:None) ^authtoken/token/>'
DEBUG 2017-08-18 07:00:46,092 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (None:None) ^enjoy_love/globalsettings/>'
DEBUG 2017-08-18 07:00:46,093 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (None:None) ^enjoy_love/advertisement/>'
DEBUG 2017-08-18 07:00:46,094 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (None:None) ^auth/user/>'
DEBUG 2017-08-18 07:00:46,094 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (None:None) ^enjoy_love/personalinterest/>'
DEBUG 2017-08-18 07:00:46,095 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (None:None) ^enjoy_love/vip/>'
DEBUG 2017-08-18 07:00:46,095 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (None:None) ^enjoy_love/identityverify/>'
DEBUG 2017-08-18 07:00:46,096 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (None:None) ^enjoy_love/contacttype/>'
DEBUG 2017-08-18 07:00:46,096 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework/urls.pyc'> (rest_framework:rest_framework) ^api-auth/>"
DEBUG 2017-08-18 07:00:46,097 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'enjoy_love.urls' from '/root/enjoylove/enjoylove/enjoy_love/urls.pyc'> (None:None) ^user/>"
DEBUG 2017-08-18 07:00:46,097 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework_docs.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework_docs/urls.pyc'> (None:None) ^docs/>"
DEBUG 2017-08-18 07:00:46,168 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'grappelli.urls' from '/root/enjoylove/lib/python2.7/site-packages/grappelli/urls.pyc'> (None:None) ^grappelli/>"
DEBUG 2017-08-18 07:00:46,170 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (None:None) ^auth/group/>'
DEBUG 2017-08-18 07:00:46,170 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (None:None) ^enjoy_love/filtercontrol/>'
DEBUG 2017-08-18 07:00:46,171 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (None:None) ^enjoy_love/personaltag/>'
DEBUG 2017-08-18 07:00:46,171 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (None:None) ^authtoken/token/>'
DEBUG 2017-08-18 07:00:46,172 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (None:None) ^enjoy_love/globalsettings/>'
DEBUG 2017-08-18 07:00:46,172 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (None:None) ^enjoy_love/advertisement/>'
DEBUG 2017-08-18 07:00:46,172 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (None:None) ^auth/user/>'
DEBUG 2017-08-18 07:00:46,173 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (None:None) ^enjoy_love/personalinterest/>'
DEBUG 2017-08-18 07:00:46,173 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (None:None) ^enjoy_love/vip/>'
DEBUG 2017-08-18 07:00:46,174 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (None:None) ^enjoy_love/identityverify/>'
DEBUG 2017-08-18 07:00:46,174 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (None:None) ^enjoy_love/contacttype/>'
DEBUG 2017-08-18 07:00:46,175 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework/urls.pyc'> (rest_framework:rest_framework) ^api-auth/>"
DEBUG 2017-08-18 07:00:46,175 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'enjoy_love.urls' from '/root/enjoylove/enjoylove/enjoy_love/urls.pyc'> (None:None) ^user/>"
DEBUG 2017-08-18 07:00:46,176 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework_docs.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework_docs/urls.pyc'> (None:None) ^docs/>"
DEBUG 2017-08-18 07:00:46,234 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'grappelli.urls' from '/root/enjoylove/lib/python2.7/site-packages/grappelli/urls.pyc'> (None:None) ^grappelli/>"
DEBUG 2017-08-18 07:00:46,236 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (None:None) ^auth/group/>'
DEBUG 2017-08-18 07:00:46,236 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (None:None) ^enjoy_love/filtercontrol/>'
DEBUG 2017-08-18 07:00:46,237 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (None:None) ^enjoy_love/personaltag/>'
DEBUG 2017-08-18 07:00:46,237 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (None:None) ^authtoken/token/>'
DEBUG 2017-08-18 07:00:46,238 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (None:None) ^enjoy_love/globalsettings/>'
DEBUG 2017-08-18 07:00:46,238 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (None:None) ^enjoy_love/advertisement/>'
DEBUG 2017-08-18 07:00:46,239 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (None:None) ^auth/user/>'
DEBUG 2017-08-18 07:00:46,239 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (None:None) ^enjoy_love/personalinterest/>'
DEBUG 2017-08-18 07:00:46,240 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (None:None) ^enjoy_love/vip/>'
DEBUG 2017-08-18 07:00:46,241 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (None:None) ^enjoy_love/identityverify/>'
DEBUG 2017-08-18 07:00:46,241 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (None:None) ^enjoy_love/contacttype/>'
DEBUG 2017-08-18 07:00:46,242 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework/urls.pyc'> (rest_framework:rest_framework) ^api-auth/>"
DEBUG 2017-08-18 07:00:46,242 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'enjoy_love.urls' from '/root/enjoylove/enjoylove/enjoy_love/urls.pyc'> (None:None) ^user/>"
DEBUG 2017-08-18 07:00:46,243 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework_docs.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework_docs/urls.pyc'> (None:None) ^docs/>"
DEBUG 2017-08-18 07:00:46,505 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'grappelli.urls' from '/root/enjoylove/lib/python2.7/site-packages/grappelli/urls.pyc'> (None:None) ^grappelli/>"
DEBUG 2017-08-18 07:00:46,506 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
DEBUG 2017-08-18 07:00:46,506 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework/urls.pyc'> (rest_framework:rest_framework) ^api-auth/>"
DEBUG 2017-08-18 07:00:46,507 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'enjoy_love.urls' from '/root/enjoylove/enjoylove/enjoy_love/urls.pyc'> (None:None) ^user/>"
DEBUG 2017-08-18 07:00:46,507 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework_docs.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework_docs/urls.pyc'> (None:None) ^docs/>"
DEBUG 2017-08-18 07:00:47,117 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'grappelli.urls' from '/root/enjoylove/lib/python2.7/site-packages/grappelli/urls.pyc'> (None:None) ^grappelli/>"
DEBUG 2017-08-18 07:00:47,117 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
DEBUG 2017-08-18 07:00:47,118 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework/urls.pyc'> (rest_framework:rest_framework) ^api-auth/>"
DEBUG 2017-08-18 07:00:47,118 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'enjoy_love.urls' from '/root/enjoylove/enjoylove/enjoy_love/urls.pyc'> (None:None) ^user/>"
DEBUG 2017-08-18 07:00:47,119 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework_docs.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework_docs/urls.pyc'> (None:None) ^docs/>"
DEBUG 2017-08-18 07:00:47,350 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'grappelli.urls' from '/root/enjoylove/lib/python2.7/site-packages/grappelli/urls.pyc'> (None:None) ^grappelli/>"
DEBUG 2017-08-18 07:00:47,350 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
DEBUG 2017-08-18 07:00:47,350 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework/urls.pyc'> (rest_framework:rest_framework) ^api-auth/>"
DEBUG 2017-08-18 07:00:47,351 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'enjoy_love.urls' from '/root/enjoylove/enjoylove/enjoy_love/urls.pyc'> (None:None) ^user/>"
DEBUG 2017-08-18 07:00:47,351 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework_docs.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework_docs/urls.pyc'> (None:None) ^docs/>"
DEBUG 2017-08-18 07:00:47,426 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'grappelli.urls' from '/root/enjoylove/lib/python2.7/site-packages/grappelli/urls.pyc'> (None:None) ^grappelli/>"
DEBUG 2017-08-18 07:00:47,427 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
DEBUG 2017-08-18 07:00:47,427 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework/urls.pyc'> (rest_framework:rest_framework) ^api-auth/>"
DEBUG 2017-08-18 07:00:47,428 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'enjoy_love.urls' from '/root/enjoylove/enjoylove/enjoy_love/urls.pyc'> (None:None) ^user/>"
DEBUG 2017-08-18 07:00:47,428 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework_docs.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework_docs/urls.pyc'> (None:None) ^docs/>"
DEBUG 2017-08-18 07:00:47,919 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'grappelli.urls' from '/root/enjoylove/lib/python2.7/site-packages/grappelli/urls.pyc'> (None:None) ^grappelli/>"
DEBUG 2017-08-18 07:00:47,920 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
DEBUG 2017-08-18 07:00:47,920 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework/urls.pyc'> (rest_framework:rest_framework) ^api-auth/>"
DEBUG 2017-08-18 07:00:47,921 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'enjoy_love.urls' from '/root/enjoylove/enjoylove/enjoy_love/urls.pyc'> (None:None) ^user/>"
DEBUG 2017-08-18 07:00:47,921 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework_docs.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework_docs/urls.pyc'> (None:None) ^docs/>"
DEBUG 2017-08-18 07:00:48,125 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'grappelli.urls' from '/root/enjoylove/lib/python2.7/site-packages/grappelli/urls.pyc'> (None:None) ^grappelli/>"
DEBUG 2017-08-18 07:00:48,126 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
DEBUG 2017-08-18 07:00:48,126 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework/urls.pyc'> (rest_framework:rest_framework) ^api-auth/>"
DEBUG 2017-08-18 07:00:48,127 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'enjoy_love.urls' from '/root/enjoylove/enjoylove/enjoy_love/urls.pyc'> (None:None) ^user/>"
DEBUG 2017-08-18 07:00:48,127 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework_docs.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework_docs/urls.pyc'> (None:None) ^docs/>"
DEBUG 2017-08-18 07:00:48,192 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'grappelli.urls' from '/root/enjoylove/lib/python2.7/site-packages/grappelli/urls.pyc'> (None:None) ^grappelli/>"
DEBUG 2017-08-18 07:00:48,193 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
DEBUG 2017-08-18 07:00:48,193 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework/urls.pyc'> (rest_framework:rest_framework) ^api-auth/>"
DEBUG 2017-08-18 07:00:48,194 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'enjoy_love.urls' from '/root/enjoylove/enjoylove/enjoy_love/urls.pyc'> (None:None) ^user/>"
DEBUG 2017-08-18 07:00:48,194 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework_docs.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework_docs/urls.pyc'> (None:None) ^docs/>"
DEBUG 2017-08-18 07:00:48,262 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'grappelli.urls' from '/root/enjoylove/lib/python2.7/site-packages/grappelli/urls.pyc'> (None:None) ^grappelli/>"
DEBUG 2017-08-18 07:00:48,262 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
DEBUG 2017-08-18 07:00:48,263 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework/urls.pyc'> (rest_framework:rest_framework) ^api-auth/>"
DEBUG 2017-08-18 07:00:48,263 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'enjoy_love.urls' from '/root/enjoylove/enjoylove/enjoy_love/urls.pyc'> (None:None) ^user/>"
DEBUG 2017-08-18 07:00:48,264 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework_docs.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework_docs/urls.pyc'> (None:None) ^docs/>"
DEBUG 2017-08-18 07:00:48,580 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'grappelli.urls' from '/root/enjoylove/lib/python2.7/site-packages/grappelli/urls.pyc'> (None:None) ^grappelli/>"
DEBUG 2017-08-18 07:00:48,581 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
DEBUG 2017-08-18 07:00:48,581 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework/urls.pyc'> (rest_framework:rest_framework) ^api-auth/>"
DEBUG 2017-08-18 07:00:48,582 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'enjoy_love.urls' from '/root/enjoylove/enjoylove/enjoy_love/urls.pyc'> (None:None) ^user/>"
DEBUG 2017-08-18 07:00:48,583 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework_docs.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework_docs/urls.pyc'> (None:None) ^docs/>"
DEBUG 2017-08-18 07:00:48,745 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'grappelli.urls' from '/root/enjoylove/lib/python2.7/site-packages/grappelli/urls.pyc'> (None:None) ^grappelli/>"
DEBUG 2017-08-18 07:00:48,745 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
DEBUG 2017-08-18 07:00:48,745 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework/urls.pyc'> (rest_framework:rest_framework) ^api-auth/>"
DEBUG 2017-08-18 07:00:48,746 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'enjoy_love.urls' from '/root/enjoylove/enjoylove/enjoy_love/urls.pyc'> (None:None) ^user/>"
DEBUG 2017-08-18 07:00:48,746 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework_docs.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework_docs/urls.pyc'> (None:None) ^docs/>"
DEBUG 2017-08-18 07:00:48,825 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'grappelli.urls' from '/root/enjoylove/lib/python2.7/site-packages/grappelli/urls.pyc'> (None:None) ^grappelli/>"
DEBUG 2017-08-18 07:00:48,825 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
DEBUG 2017-08-18 07:00:48,826 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework/urls.pyc'> (rest_framework:rest_framework) ^api-auth/>"
DEBUG 2017-08-18 07:00:48,826 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'enjoy_love.urls' from '/root/enjoylove/enjoylove/enjoy_love/urls.pyc'> (None:None) ^user/>"
DEBUG 2017-08-18 07:00:48,827 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework_docs.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework_docs/urls.pyc'> (None:None) ^docs/>"
DEBUG 2017-08-18 07:00:48,904 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'grappelli.urls' from '/root/enjoylove/lib/python2.7/site-packages/grappelli/urls.pyc'> (None:None) ^grappelli/>"
DEBUG 2017-08-18 07:00:48,904 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
DEBUG 2017-08-18 07:00:48,905 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework/urls.pyc'> (rest_framework:rest_framework) ^api-auth/>"
DEBUG 2017-08-18 07:00:48,905 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'enjoy_love.urls' from '/root/enjoylove/enjoylove/enjoy_love/urls.pyc'> (None:None) ^user/>"
DEBUG 2017-08-18 07:00:48,906 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework_docs.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework_docs/urls.pyc'> (None:None) ^docs/>"
DEBUG 2017-08-18 07:00:49,197 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'grappelli.urls' from '/root/enjoylove/lib/python2.7/site-packages/grappelli/urls.pyc'> (None:None) ^grappelli/>"
DEBUG 2017-08-18 07:00:49,198 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
DEBUG 2017-08-18 07:00:49,198 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework/urls.pyc'> (rest_framework:rest_framework) ^api-auth/>"
DEBUG 2017-08-18 07:00:49,199 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'enjoy_love.urls' from '/root/enjoylove/enjoylove/enjoy_love/urls.pyc'> (None:None) ^user/>"
DEBUG 2017-08-18 07:00:49,199 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework_docs.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework_docs/urls.pyc'> (None:None) ^docs/>"
DEBUG 2017-08-18 07:00:49,343 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'grappelli.urls' from '/root/enjoylove/lib/python2.7/site-packages/grappelli/urls.pyc'> (None:None) ^grappelli/>"
DEBUG 2017-08-18 07:00:49,344 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
DEBUG 2017-08-18 07:00:49,344 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework/urls.pyc'> (rest_framework:rest_framework) ^api-auth/>"
DEBUG 2017-08-18 07:00:49,345 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'enjoy_love.urls' from '/root/enjoylove/enjoylove/enjoy_love/urls.pyc'> (None:None) ^user/>"
DEBUG 2017-08-18 07:00:49,345 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework_docs.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework_docs/urls.pyc'> (None:None) ^docs/>"
DEBUG 2017-08-18 07:00:49,860 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'grappelli.urls' from '/root/enjoylove/lib/python2.7/site-packages/grappelli/urls.pyc'> (None:None) ^grappelli/>"
DEBUG 2017-08-18 07:00:49,861 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
DEBUG 2017-08-18 07:00:49,862 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework/urls.pyc'> (rest_framework:rest_framework) ^api-auth/>"
DEBUG 2017-08-18 07:00:49,862 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'enjoy_love.urls' from '/root/enjoylove/enjoylove/enjoy_love/urls.pyc'> (None:None) ^user/>"
DEBUG 2017-08-18 07:00:49,863 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework_docs.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework_docs/urls.pyc'> (None:None) ^docs/>"
DEBUG 2017-08-18 07:00:50,157 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'grappelli.urls' from '/root/enjoylove/lib/python2.7/site-packages/grappelli/urls.pyc'> (None:None) ^grappelli/>"
DEBUG 2017-08-18 07:00:50,157 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
DEBUG 2017-08-18 07:00:50,158 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework/urls.pyc'> (rest_framework:rest_framework) ^api-auth/>"
DEBUG 2017-08-18 07:00:50,159 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'enjoy_love.urls' from '/root/enjoylove/enjoylove/enjoy_love/urls.pyc'> (None:None) ^user/>"
DEBUG 2017-08-18 07:00:50,159 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework_docs.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework_docs/urls.pyc'> (None:None) ^docs/>"
DEBUG 2017-08-18 07:00:50,226 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'grappelli.urls' from '/root/enjoylove/lib/python2.7/site-packages/grappelli/urls.pyc'> (None:None) ^grappelli/>"
DEBUG 2017-08-18 07:00:50,227 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
DEBUG 2017-08-18 07:00:50,227 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework/urls.pyc'> (rest_framework:rest_framework) ^api-auth/>"
DEBUG 2017-08-18 07:00:50,228 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'enjoy_love.urls' from '/root/enjoylove/enjoylove/enjoy_love/urls.pyc'> (None:None) ^user/>"
DEBUG 2017-08-18 07:00:50,228 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework_docs.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework_docs/urls.pyc'> (None:None) ^docs/>"
DEBUG 2017-08-18 07:00:50,438 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'grappelli.urls' from '/root/enjoylove/lib/python2.7/site-packages/grappelli/urls.pyc'> (None:None) ^grappelli/>"
DEBUG 2017-08-18 07:00:50,439 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
DEBUG 2017-08-18 07:00:50,439 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework/urls.pyc'> (rest_framework:rest_framework) ^api-auth/>"
DEBUG 2017-08-18 07:00:50,440 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'enjoy_love.urls' from '/root/enjoylove/enjoylove/enjoy_love/urls.pyc'> (None:None) ^user/>"
DEBUG 2017-08-18 07:00:50,440 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework_docs.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework_docs/urls.pyc'> (None:None) ^docs/>"
DEBUG 2017-08-18 07:00:52,040 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'grappelli.urls' from '/root/enjoylove/lib/python2.7/site-packages/grappelli/urls.pyc'> (None:None) ^grappelli/>"
DEBUG 2017-08-18 07:00:52,041 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
DEBUG 2017-08-18 07:00:52,042 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework/urls.pyc'> (rest_framework:rest_framework) ^api-auth/>"
DEBUG 2017-08-18 07:00:52,042 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'enjoy_love.urls' from '/root/enjoylove/enjoylove/enjoy_love/urls.pyc'> (None:None) ^user/>"
DEBUG 2017-08-18 07:00:52,043 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework_docs.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework_docs/urls.pyc'> (None:None) ^docs/>"
DEBUG 2017-08-18 07:00:52,307 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'grappelli.urls' from '/root/enjoylove/lib/python2.7/site-packages/grappelli/urls.pyc'> (None:None) ^grappelli/>"
DEBUG 2017-08-18 07:00:52,308 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
DEBUG 2017-08-18 07:00:52,309 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework/urls.pyc'> (rest_framework:rest_framework) ^api-auth/>"
DEBUG 2017-08-18 07:00:52,309 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'enjoy_love.urls' from '/root/enjoylove/enjoylove/enjoy_love/urls.pyc'> (None:None) ^user/>"
DEBUG 2017-08-18 07:00:52,310 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework_docs.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework_docs/urls.pyc'> (None:None) ^docs/>"
DEBUG 2017-08-18 07:00:52,591 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'grappelli.urls' from '/root/enjoylove/lib/python2.7/site-packages/grappelli/urls.pyc'> (None:None) ^grappelli/>"
DEBUG 2017-08-18 07:00:52,591 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
DEBUG 2017-08-18 07:00:52,592 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework/urls.pyc'> (rest_framework:rest_framework) ^api-auth/>"
DEBUG 2017-08-18 07:00:52,592 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'enjoy_love.urls' from '/root/enjoylove/enjoylove/enjoy_love/urls.pyc'> (None:None) ^user/>"
DEBUG 2017-08-18 07:00:52,593 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework_docs.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework_docs/urls.pyc'> (None:None) ^docs/>"
DEBUG 2017-08-18 07:00:53,681 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'grappelli.urls' from '/root/enjoylove/lib/python2.7/site-packages/grappelli/urls.pyc'> (None:None) ^grappelli/>"
DEBUG 2017-08-18 07:00:53,682 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
DEBUG 2017-08-18 07:00:53,682 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework/urls.pyc'> (rest_framework:rest_framework) ^api-auth/>"
DEBUG 2017-08-18 07:00:53,683 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'enjoy_love.urls' from '/root/enjoylove/enjoylove/enjoy_love/urls.pyc'> (None:None) ^user/>"
DEBUG 2017-08-18 07:00:53,683 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework_docs.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework_docs/urls.pyc'> (None:None) ^docs/>"
DEBUG 2017-08-18 07:00:53,753 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'grappelli.urls' from '/root/enjoylove/lib/python2.7/site-packages/grappelli/urls.pyc'> (None:None) ^grappelli/>"
DEBUG 2017-08-18 07:00:53,753 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
DEBUG 2017-08-18 07:00:53,754 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework/urls.pyc'> (rest_framework:rest_framework) ^api-auth/>"
DEBUG 2017-08-18 07:00:53,754 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'enjoy_love.urls' from '/root/enjoylove/enjoylove/enjoy_love/urls.pyc'> (None:None) ^user/>"
DEBUG 2017-08-18 07:00:53,755 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework_docs.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework_docs/urls.pyc'> (None:None) ^docs/>"
DEBUG 2017-08-18 07:00:54,005 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'grappelli.urls' from '/root/enjoylove/lib/python2.7/site-packages/grappelli/urls.pyc'> (None:None) ^grappelli/>"
DEBUG 2017-08-18 07:00:54,006 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
DEBUG 2017-08-18 07:00:54,007 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework/urls.pyc'> (rest_framework:rest_framework) ^api-auth/>"
DEBUG 2017-08-18 07:00:54,007 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'enjoy_love.urls' from '/root/enjoylove/enjoylove/enjoy_love/urls.pyc'> (None:None) ^user/>"
DEBUG 2017-08-18 07:00:54,008 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework_docs.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework_docs/urls.pyc'> (None:None) ^docs/>"
DEBUG 2017-08-18 07:00:54,385 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'grappelli.urls' from '/root/enjoylove/lib/python2.7/site-packages/grappelli/urls.pyc'> (None:None) ^grappelli/>"
DEBUG 2017-08-18 07:00:54,386 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
DEBUG 2017-08-18 07:00:54,387 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework/urls.pyc'> (rest_framework:rest_framework) ^api-auth/>"
DEBUG 2017-08-18 07:00:54,387 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'enjoy_love.urls' from '/root/enjoylove/enjoylove/enjoy_love/urls.pyc'> (None:None) ^user/>"
DEBUG 2017-08-18 07:00:54,388 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework_docs.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework_docs/urls.pyc'> (None:None) ^docs/>"
DEBUG 2017-08-18 07:00:54,483 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'grappelli.urls' from '/root/enjoylove/lib/python2.7/site-packages/grappelli/urls.pyc'> (None:None) ^grappelli/>"
DEBUG 2017-08-18 07:00:54,484 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
DEBUG 2017-08-18 07:00:54,484 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework/urls.pyc'> (rest_framework:rest_framework) ^api-auth/>"
DEBUG 2017-08-18 07:00:54,485 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'enjoy_love.urls' from '/root/enjoylove/enjoylove/enjoy_love/urls.pyc'> (None:None) ^user/>"
DEBUG 2017-08-18 07:00:54,485 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework_docs.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework_docs/urls.pyc'> (None:None) ^docs/>"
DEBUG 2017-08-18 07:00:54,555 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'grappelli.urls' from '/root/enjoylove/lib/python2.7/site-packages/grappelli/urls.pyc'> (None:None) ^grappelli/>"
DEBUG 2017-08-18 07:00:54,556 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
DEBUG 2017-08-18 07:00:54,556 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework/urls.pyc'> (rest_framework:rest_framework) ^api-auth/>"
DEBUG 2017-08-18 07:00:54,557 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'enjoy_love.urls' from '/root/enjoylove/enjoylove/enjoy_love/urls.pyc'> (None:None) ^user/>"
DEBUG 2017-08-18 07:00:54,557 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework_docs.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework_docs/urls.pyc'> (None:None) ^docs/>"
DEBUG 2017-08-18 07:00:54,634 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'grappelli.urls' from '/root/enjoylove/lib/python2.7/site-packages/grappelli/urls.pyc'> (None:None) ^grappelli/>"
DEBUG 2017-08-18 07:00:54,634 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
DEBUG 2017-08-18 07:00:54,635 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework/urls.pyc'> (rest_framework:rest_framework) ^api-auth/>"
DEBUG 2017-08-18 07:00:54,635 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'enjoy_love.urls' from '/root/enjoylove/enjoylove/enjoy_love/urls.pyc'> (None:None) ^user/>"
DEBUG 2017-08-18 07:00:54,636 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework_docs.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework_docs/urls.pyc'> (None:None) ^docs/>"
DEBUG 2017-08-18 07:00:54,704 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'grappelli.urls' from '/root/enjoylove/lib/python2.7/site-packages/grappelli/urls.pyc'> (None:None) ^grappelli/>"
DEBUG 2017-08-18 07:00:54,704 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
DEBUG 2017-08-18 07:00:54,705 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework/urls.pyc'> (rest_framework:rest_framework) ^api-auth/>"
DEBUG 2017-08-18 07:00:54,705 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'enjoy_love.urls' from '/root/enjoylove/enjoylove/enjoy_love/urls.pyc'> (None:None) ^user/>"
DEBUG 2017-08-18 07:00:54,706 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework_docs.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework_docs/urls.pyc'> (None:None) ^docs/>"
DEBUG 2017-08-18 07:00:54,775 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'grappelli.urls' from '/root/enjoylove/lib/python2.7/site-packages/grappelli/urls.pyc'> (None:None) ^grappelli/>"
DEBUG 2017-08-18 07:00:54,775 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
DEBUG 2017-08-18 07:00:54,776 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework/urls.pyc'> (rest_framework:rest_framework) ^api-auth/>"
DEBUG 2017-08-18 07:00:54,776 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'enjoy_love.urls' from '/root/enjoylove/enjoylove/enjoy_love/urls.pyc'> (None:None) ^user/>"
DEBUG 2017-08-18 07:00:54,777 /root/enjoylove/lib/python2.7/site-packages/django/template/base.py base.py base _resolve_lookup 925: Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/root/enjoylove/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'rest_framework_docs.urls' from '/root/enjoylove/lib/python2.7/site-packages/rest_framework_docs/urls.pyc'> (None:None) ^docs/>"
